@host = http://localhost:4000/
@cpf1 = 047.080.070-43
@cpf2 = 648.432.950-86
@cpf3 = 295.581.050-90
@pass = pass1234

# @name register
POST {{ host }}api/accounts HTTP/1.1
content-type: application/json

{
    "name": "Joana Doe",
    "cpf": "{{ cpf1 }}",
    "password": "{{ pass }}"
}

###

# @name login
POST {{ host }}api/accounts/login HTTP/1.1
content-type: application/json

{
    "cpf": "{{ cpf1 }}",
    "password": "{{ pass }}"
}

###

# @name profile
GET {{ host }}api/accounts/me HTTP/1.1
content-type: application/json
Authorization: Bearer {{ login.response.body.access }}

###

# @name list_transactions
GET {{ host }}api/transactions?date_start=2021-05-05&date_end=2021-10-10 HTTP/1.1
content-type: application/json
Authorization: Bearer {{ login.response.body.access }}

###

# @name new_transaction
POST {{ host }}api/transactions HTTP/1.1
content-type: application/json
Authorization: Bearer {{ login.response.body.access }}

{
    "recipient_cpf": "{{ cpf2 }}",
    "amount": 500
}

###

# @name transaction_details
GET {{ host }}api/transactions/{{ new_transaction.response.body.data.id }} HTTP/1.1
content-type: application/json
Authorization: Bearer {{ login.response.body.access }}

###

# @name transaction_chargeback
POST {{ host }}api/transactions/{{ new_transaction.response.body.data.id }}/chargeback HTTP/1.1
content-type: application/json
Authorization: Bearer {{ login.response.body.access }}
